import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { SidebarProvider } from './context/SidebarContext'
import BaseLayout from './components/BaseLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <SidebarProvider>
            <BaseLayout>
              {children}
            </BaseLayout>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  )
}
